# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
        - name: auth-postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              # valueFrom:
              #   secretKeyRef:
              #     name: postgres-password
              #     key: POSTGRES_PASSWORD
              value: '1234'
            - name: POSTGRES_USER
              # valueFrom:
              #   secretKeyRef:
              #     name: postgres-user
              #     key: POSTGRES_USER
              value: 'postgres'
            - name: POSTGRES_DB
              # valueFrom:
              #   secretKeyRef:
              #     name: postgres-db
              #     key: POSTGRES_DB
              value: 'Auth'
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres-srv
spec:
  selector:
    app: auth-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
