kubectl create secret generic chat-secrets --from-literal=MONGO_URL="mongodb+srv://ranjithp27122003:qwerty1234@cluster0.akd3bfz.mongodb.net/DC-chat?retryWrites=true&w=majority"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: ranjithp007/dc_chat
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: chat-secrets
                  key: MONGO_URL

---
apiVersion: v1
kind: Service
metadata:
  name: chat-srv
spec:
  selector:
    app: chat
  ports:
    - name: chat
      protocol: TCP
      port: 3000
      targetPort: 3000
