apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classroom
  template:
    metadata:
      labels:
        app: classroom
    spec:
      containers:
        - name: classroom
          image: ranjithp007/dc_classroom
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: classroom-secrets
                  key: MONGO_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: classroom-secrets
                  key: REDIS_URL
            - name: EMAILID
              valueFrom:
                secretKeyRef:
                  name: classroom-secrets
                  key: EMAILID
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: classroom-secrets
                  key: PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_KEY      

---
apiVersion: v1
kind: Service
metadata:
  name: classroom-srv
spec:
  selector:
    app: classroom
  ports:
    - name: classroom
      protocol: TCP
      port: 3000
      targetPort: 3000
