apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission-mongo-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: submission-mongo
  template:
    metadata:
      labels:
        app: submission-mongo
    spec: 
      containers:
        - name: submission-mongo    
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: submission-mongo-srv
spec:
  selector:
    app: submission-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017