name: tests-assignment

on:
  pull_request
    paths:
      - 'assignment/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd assignment && npm install
