name: test-classroom

on:
  pull_request
    paths:
      - 'classroom/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd classroom && npm install
