name: test-submission

on:
  pull_request
    paths:
      - 'submission/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd submission && npm install
